//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaTelefonica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_contatos
    {
        public int id { get; set; }
        public string nmContato { get; set; }
        public string nr_telPrinc { get; set; }
        public string nr_telSec { get; set; }
        public string email { get; set; }
        public string notes { get; set; }
    }
}
